language: python
python:
  - "3.5"
  - "3.6"
services:
  - mysql
  - redis
script: py.test -c pytest-travis.ini
install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install coveralls
after_success:
  - coveralls
