version: "2"
services:
    mysql:
        image: mysql
        container_name: swaggerit-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: swaggerit_test
    redis:
        image: redis
        container_name: swaggerit-redis
    elsearch:
        image: elasticsearch
        container_name: swaggerit-elsearch
    swaggerit:
        build: .
        image: swaggerit
        container_name: swaggerit
        stdin_open: true
        tty: true
        depends_on:
            - mysql
            - redis
            - elsearch
        links:
            - mysql:swaggerit-mysql
            - redis:swaggerit-redis
            - elsearch:swaggerit-elsearch
        volumes:
            - $SWAGGERIT_DEV_HOME:/swaggerit
        environment:
            - TOXENV
